### ISSUE TITLE
Support Rust 2018 package renames

### ISSUE THREAD

**Issue by CryZe** [belfz/search-crates-io#4]
Such as:
```toml
[dependencies]
baz = { version = "0.1", package = "foo" }
```
foo is renamed to baz here.
